### ISSUE TITLE
Use headers instead of socket IP

### ISSUE THREAD

**Issue by spion** [spion/sticky-listen#1]
Parse the HTTP headers and use the cookie or the IP in the `x-forwarded-for` header - this should work better when there are additional load balancers between the cluster and the client.

What should the strategy be though? Cookie, fallback to x-forwarded-for, fallback to ip address? How to gracefully handle no-cookie -> cookie transition?

**Comment by Ajaxy** [comment]
Strategy looks acceptable. What do you mean by `no-cookie -> cookie transition`? Seems that we just have to round-robin the first request and set the cookie with the worker number.

What about the `sig` parameter that I mentioned? It appears to be returned by `socket.io` server for the first request and then is being added by the client to any further request. If we can handle the very first response and extract that `sig` parameter we can create some mapping table and match all further requests to the same worker as the first one. Okay now I think that's kind of overhead haha.

**Comment by spion** [comment]
@Ajaxy To add a cookie, `sticky-listen` will also have to intercept the server response and add the cookie there, not just the request. Since the socket has been handed off to the other worker already, I doubt that I can make that work at all.

I think its best to go with a simpler solution that uses the IP address in `x-forwarded-for` first... then if thats not enough we'll try to improve it incrementally

**Comment by spion** [comment]
Balancing based on `x-forwarded-for` released with v3.1. There is almost no noticeable performance loss.
