### ISSUE TITLE
Is it possible to listen to a specific IP address?

### ISSUE THREAD

**Issue by sourabhdebnath** [spion/sticky-listen#3]
Just wondering if there is a way to pass the IP address to the balancer to listen to,  just as we pass the port ? In express we would do something like 

  app.listen(8080, '192.168.0.11');

Can we do something similar in sticky-listen?

**Comment by spion** [comment]
Not for the `listen` method, but its definitely possible to add support for it in `createBalancer`. Should be fairly easy to do...

**Comment by spion** [comment]
Oh sorry, its already possible:

``` js
var balancer = sticky.createBalancer(...)
balancer.listen(arguments...)
```

The arguments that you can pass to `balancer.listen` are the ones that are available for `net.Server` so you can use this overload:

https://nodejs.org/api/net.html#net_server_listen_port_hostname_backlog_callback

**Comment by sourabhdebnath** [comment]
Yes, even I figured that out while digging into the code. Thanks :)
