### ISSUE TITLE
Balancer listening before workers are ready.

### ISSUE THREAD

**Issue by odelrio** [spion/sticky-listen#4]
Hi.

Thank you @spion for your great module. I have copy-pasted your example and I'm worried about the fact that balancer.listen() callback is running before my workers had sent the "ready" signal, even before http.createServer(). Is it normal? I would like to be able to choose when it should begin listening.

Thank you.

**Comment by spion** [comment]
Thats a good point. recluster's `activeWorkers` only returns the workers that have indicated they're ready to work - if not, there is a `null` in that slot. If sticky-listen gets a `null`, it waits `retryDelay` miliseconds (150 is default) then tries again. It does this upto `maxRetries` times (default 5).

This is probably still not really great if you anticipate bigger delays, so I guess you could do something like this

``` js
cluster.on('ready', function onReadyListen() {
  var active = cluster.activeWorkers();
  for (var k = 0; k < active.length; ++k) if (active[k] == null) return;
  cluster.removeListener('ready', onReadyListen)
  balancer.listen(...)
});
```

to make sure listening starts only when all worker slots are active.

**Comment by odelrio** [comment]
That example worked perfectly! But my problem is not about big delays. Before your fix, at the moment of **listening**, cluster.activeWorkers() outputs `{ length: 4 }`, while when actually ready, the output is like:

```
{
    '0': Worker { id: 1, state: 'listening',... },
    '1': Worker { id: 2, state: 'listening',... },
    '2': Worker { id: 3, state: 'listening',... },
    '3': Worker { id: 4, state: 'listening',... },
    length: 4
}
```

Is that the expected behavior?

Thank you.

**Comment by spion** [comment]
Yes it is, length is just the size of the worker pool (number of worker slots). Slots that aren't ready at the moment are normally null or undefined - if undefined they wont appear.

**Comment by odelrio** [comment]
Ok :+1:

Thank you again.
