### ISSUE TITLE
Responsible worker is some how becoming null and thus error - 502 

### ISSUE THREAD

**Issue by nautiyalanuj** [spion/sticky-listen#9]
Hi spion first Thanks for your code.

I have trying to use your code in my project and it's working fine. But when I starts/restart my node server and socket server many times it is getting struck in loop of 
> function Master.prototype.delegate()
>       socket.end('HTTP/1.0 502 Bad Gateway\n\n')

	  
  i.e responsible worker is some how becoming null and thus when client try to connect it doesn't get any worker and client keep on trying.
  So could you tell how to resolve this problem??

  
Worker Code

```
const http = require('http');
const socketServer = require('socket.io');
const sticky = require('sticky-listen');

const server = http.createServer();
const options = {
  pingTimeout: 100000,
  pingInterval: 20000,    
};
const io = socketServer(server, options);
sticky.listen(server);
io.adapter(soredis({host: host, port: port}));
process.send({cmd: 'ready'});
```

Server Code

 ```
 var filename; // above file
  var opts = {
    timeout: 30,
    respawn: 60,
    readyWhen: 'ready'
  };

  var cluster = recluster(filename, opts);
  cluster.run();
  
  /**
    * Code added for sticky sessions in cluster mode
    */
  var balancer = sticky.createBalancer({
    behindProxy: false,
    activeWorkers: cluster.activeWorkers,
    maxRetries: 3,
    retryDelay: 100
  });  

  /*So only starts listening when all worker ready*/
  cluster.on('ready', function onReadyListen() {
    var active = cluster.activeWorkers();
    for (var k = 0; k < active.length; ++k) {
      if (active[k] === null) {
        return;
      }
    }    
    cluster.removeListener('ready', onReadyListen);
    balancer.listen(3000, function() {
      console.log("Sticky balancer listening on port", 3000);
    });
  });
```

**Comment by spion** [comment]
Try increasing maxRetries and retryDelay. With the current settings if your node process needs more than 3x100ms = 300ms to restart you would get 502 errors.

**Comment by nautiyalanuj** [comment]
Strangely no such issue occurring now. If reproduced again will try as per your comment. Thanks for your speedy response :)
